import { type NextPage } from "next";
import Head from "next/head";
import Navbar from "~/components/index/navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Discord | Your Place to Talk and Hang Out</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={"min-h-[626px] bg-[#404eed]"}>
        <Navbar />
      </main>
    </>
  );
};

export default Home;
